version: '3'

services:
  postgres:
    image: postgres:14.9
    container_name: postgres
    environment:
      - ENVIRONMENT=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    network_mode: bridge